name: Waka Readme

on:
  repository_dispatch:
    types: [test_trigger]
  workflow_dispatch:
  schedule:
    # Runs at 4am JST
    - cron: '30 19 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_PROFILE_VIEWS: "False"
#       - uses: athul/waka-readme@master
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

  update-image:
    name: Update the summary image
    runs-on: ubuntu-18.04
    steps:
      - uses: tariksahni/coding-stats-wakatime@v1.0.0
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_MONTHLY: true
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_ACTION: ${{ github.action }}
